In [5]:
import numpy as np

a = {}

a[1] = 2
a[3] = np.zeros((3, 4), dtype=int)

print(a)

{1: 2, 3: array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])}


In [3]:
# 辞書の定義
my_dict = {
    1: 10,
    2: 20,
    3: 30
}

print(my_dict[1])

10


In [3]:
import numpy as np

value = 7  # 任意の値
array_full = np.full((50, 1), value)
print(array_full)

[[7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]
 [7]]


In [6]:
a[-4] = array_full

In [11]:
a

{1: 2,
 3: array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 -4: array([[17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17],
        [17]])}

In [12]:
a[-4]+=(10-2)
print(a)

{1: 2, 3: array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), -4: array([[25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25],
       [25]])}


In [16]:
noise_x = np.random.normal(0, 3, (50, 1))
print(noise_x)

[[ 0.52204318]
 [ 1.7168413 ]
 [ 1.08158207]
 [ 1.3465045 ]
 [-0.37129212]
 [-0.35537483]
 [ 1.72441048]
 [-0.43832695]
 [ 2.67508634]
 [ 1.41626568]
 [ 0.09543272]
 [-2.13891993]
 [-3.32155514]
 [ 1.32952068]
 [ 2.4658952 ]
 [ 5.36119429]
 [ 1.86688513]
 [-1.33253713]
 [ 2.19010437]
 [ 1.64241813]
 [-0.27676083]
 [ 3.66328018]
 [ 5.22494693]
 [-0.58486578]
 [ 4.78768439]
 [ 4.32162517]
 [-2.82827033]
 [ 0.7886154 ]
 [ 0.9213304 ]
 [ 1.20340907]
 [ 2.0725281 ]
 [-0.55476275]
 [-1.3592038 ]
 [ 1.37463967]
 [ 2.40373566]
 [ 3.63228166]
 [ 1.70855629]
 [ 3.77860581]
 [ 3.22857255]
 [-4.09315747]
 [ 2.96781977]
 [-0.89486129]
 [-1.14216337]
 [-0.15747865]
 [-1.90899267]
 [-3.39493955]
 [ 1.20650089]
 [ 2.76254097]
 [ 3.12240507]
 [ 0.26318637]]


In [15]:
array_full = np.full((50, 1), value)

print(array_full.shape)
print(noise_x.shape)

(50, 1)
(50, 1)


In [21]:
a = {}

array_full = np.full((50, 1), 1)
a[-1] = array_full
array_full = np.full((50, 1), 2)
a[-2] = array_full
array_full = np.full((50, 1), 3)
a[-3] = array_full

In [23]:
for i in a:
    print(i)
a.pop(-1)
for i in a:
    print(i)

-1
-2
-3
-2
-3


In [20]:
my_list = [[1], [2], [3]]

# 要素 [2] のインデックスを取得
index_of_2 = my_list.index([2])

print(index_of_2)

1


In [26]:
a = [{}, {}]

a[1][1] = 10
a[0][0] = 20

print(a)

[{0: 20}, {1: 10}]


In [30]:
for i in a:
    print(i)
    b = i.values()
    print(list(b))

{0: 20}
[20]
{1: 10}
[10]


In [12]:
import numpy as np

# 定義された配列 a と b
a = np.array([[2.],
                    [3.],
                    [4.],
                    [5.],
                    [6.],
                    [7.],
                    [8.],
                    [9.],
                    [10.],
                    [11.],
                    [1.]])

b = np.array([[1.],
              [2.],
              [3.],
              [4.],
              [5.],
              [6.],
              [7.],
              [8.],
              [9.],
              [10.],
              [11.]])

# a をソートし、そのインデックスを取得
sorted_indices = np.argsort(a, axis=0).flatten()

# インデックスに基づいて b を再配置
sorted_b = b[sorted_indices]

print("Sorted a:")
print(np.sort(a, axis=0))

print("Correspondingly sorted b:")
print(sorted_b)


Sorted a:
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]]
Correspondingly sorted b:
[[11.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [13]:
sorted_indices

array([10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [16]:
import numpy as np

# 定義された配列 a と b
a = np.array([[5.],
                    [3.],
                    [4.]])

b = np.array([1, 2, 3])

# a をソートし、そのインデックスを取得
sorted_indices = np.argsort(a, axis=0).flatten()

# インデックスに基づいて b を再配置
sorted_b = b[sorted_indices]

print("Sorted a:")
print(np.sort(a, axis=0))

print("Correspondingly sorted b:")
print(sorted_b)

Sorted a:
[[3.]
 [4.]
 [5.]]
Correspondingly sorted b:
[2 3 1]


In [18]:
removed_id = [[7, 9], [10, 7], [9, 10]]

result_dict = {}
for sublist in removed_id:
    sublist.sort()
    key = sublist[0]
    if key in result_dict:
        result_dict[key].extend(sublist[1:])
    else:
        result_dict[key] = sublist
removed_id = list(result_dict.values())

print(removed_id)

[[7, 9, 10], [9, 10]]


In [20]:
a = [[1, 2]]
b = a.copy()

if a==b:
    print('ok')

ok


In [21]:
a = [[1, 2], [3, 4], [4, 5, 6], [10, 11, 12]]

# リスト内包表記を使用して平坦化
flattened_a = [item for sublist in a for item in sublist]

print(flattened_a)

[1, 2, 3, 4, 4, 5, 6, 10, 11, 12]


In [34]:
import numpy as np

# 元の配列
a = np.array([197., 222., 249., 253., 258., 259., 265., 270., 272., 273., 274.])

# 要素を追加
a_with_100 = np.append(a, 100)

print(a_with_100)

[197. 222. 249. 253. 258. 259. 265. 270. 272. 273. 274. 100.]


In [35]:
a = np.array([[197.],
              [222.],
              [249.],
              [253.],
              [258.],
              [259.],
              [265.],
              [270.],
              [272.],
              [273.],
              [274.]])

# id_numをソートし、そのインデックスを取得
flattened_a = a.flatten()

print(flattened_a.shape)

b = np.append(flattened_a, 100)
print(b)

(11,)
[197. 222. 249. 253. 258. 259. 265. 270. 272. 273. 274. 100.]


In [38]:
import numpy as np

# 元の配列
a = np.array([[197.],
              [222.],
              [249.]])

b = np.array([[1, 2, 3, 3],
              [2, 3, 4, 5],
              [3, 4, 5, 6]])

# 削除するインデックス
idx = 2

# 指定されたインデックスを削除
a = np.delete(a, idx, axis=0)
b = np.delete(b, idx, axis=0)

print("Array a after deleting index 2:")
print(a)

print("Array b after deleting index 2:")
print(b)


Array a after deleting index 2:
[[197.]
 [222.]]
Array b after deleting index 2:
[[1 2 3 3]
 [2 3 4 5]]


In [39]:
import numpy as np

# 元の配列
a = np.array([[197.],
              [222.],
              [249.],
              [253.],
              [258.],
              [259.],
              [265.],
              [270.],
              [272.],
              [273.],
              [274.]])

b = np.array([[1.],
              [2.],
              [3.],
              [4.],
              [5.],
              [6.],
              [7.],
              [8.],
              [9.],
              [10.],
              [11.]])

# 削除するインデックスのリスト
indices_to_delete = [2, 3, 5]

# 指定されたインデックスを削除
a = np.delete(a, indices_to_delete, axis=0)
b = np.delete(b, indices_to_delete, axis=0)

print("Array a after deleting indices [2, 3, 5]:")
print(a)

print("Array b after deleting indices [2, 3, 5]:")
print(b)


Array a after deleting indices [2, 3, 5]:
[[197.]
 [222.]
 [258.]
 [265.]
 [270.]
 [272.]
 [273.]
 [274.]]
Array b after deleting indices [2, 3, 5]:
[[ 1.]
 [ 2.]
 [ 5.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]]
